---
driver:
  name: docker
  hostname: docker.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: docker
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - linux
        - docker
  pillars:
    top.sls:
      base:
        "*":
          - docker_debian_repo
          - docker
    docker.sls:
      docker:
        client:
          compose:
            source:
              engine: pip
  pillars-from-files:
    docker_debian_repo.sls: tests/pillar/repo_docker.sls
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux.git

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: client_compose
    provisioner:
      pillars-from-files:
        docker.sls: tests/pillar/client_compose.sls

  - name: client_container
    provisioner:
      pillars-from-files:
        docker.sls: tests/pillar/client_container.sls

  - name: host_single
    provisioner:
      pillars-from-files:
        docker.sls: tests/pillar/host_single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
