version: '3'

services:
  {%- for name, srv in services.iteritems() %}
  {%- set env_file_set = False %}
  {{ name }}:
    {%- if 'env_file' in srv.keys() %}{%- set env_file_set = True %}{%- endif %}
    {{ srv|yaml(False)|indent(4) }}
    {%- if not env_file_set and compose.environment is defined %}
    env_file: .env
    {%- endif %}
  {%- endfor %}

{%- if volumes|default({}) %}
volumes:
{%- for key, value in volumes.iteritems() %}
  {%- if value is mapping %}
  {{ key }}:
    {{ value|yaml(False)|indent(4) }}
  {%- else %}
  {{ key }}:
  {%- endif %}
{%- endfor %}
{%- endif %}


{%- if networks|default({}) %}
networks:
{%- for key, value in networks.iteritems() %}
  {%- if value is mapping %}
  {{ key }}:
    {{ value|yaml(False)|indent(4) }}
  {%- else %}
  {{ key }}:
  {%- endif %}
{%- endfor %}
{%- endif %}

{#-
  vim: syntax=jinja
-#}
